### ISSUE TITLE
Requirements Definition revision

### ISSUE THREAD

**Issue by lexykj** [palani-johnson/TheDjinns-Group10#11]
1. Introduction and Context
2. Users and their Goals
3. Functional Requirements
4. Non-functional Requirements
5. Future Features
6. Glossary

*6 points*

**Comment by christensenjo** [comment]
No revisions necessary to sections 1, 2, 4, 5, or 6

**Comment by christensenjo** [comment]
Revisions to section 2 were completed by Lexy at the end of Milestone 1/very beginning of Milestone 2 by adding the user info for each use case diagram.

**Comment by christensenjo** [comment]
Palani updated the numbering system for the functional requirements
