### ISSUE TITLE
Powerpoint slides

### ISSUE THREAD

**Issue by christensenjo** [palani-johnson/TheDjinns-Group10#113]
see Milestone 4 in Canvas

- [x] Overview
- [x] Requirement 1
- [x] Requirement 2
- [x] Requirement 3
- [x] Resources

**Comment by palani-johnson** [comment]
[Slides link](https://docs.google.com/presentation/d/1zmSE7jhQ7ZfiP49om4L5GKaqWghZEpfjNWws7HIvLUY/edit?usp=sharing)
